count = input("Enter a number")
count1 = (float(count))
count2 = input("Enter another Number")
count2_2 = (float(count2))
addition = (count1) * (count2_2)
print(f"did you know {count1} times {count2_2} = {addition}?")